### ISSUE TITLE
Replication / init_replica with an already build schema

### ISSUE THREAD

**Issue by rorhug** [the4thdoctor/pg_chameleon#112]
Hey @the4thdoctor - thanks for your work on this. 
Migrating a large app db from maria10.2 to postgres12 using chameleon!

**Is your feature request related to a problem? Please describe.**

I want to migrate our new production from the schema of our web app and just have it match and sync columns assuming the with the schema I have already initialized from our web app code.

**Describe the solution you'd like**

What I would like is to be able to `init_replica`/start replication without having pg_chameleon build the schema in my destination postgres. We are using phoenix + https://github.com/elixir-ecto/ecto . It names indexes, constraints, differently to pg chameleon.

**Describe alternatives you've considered**
About to hop into the source code and see if i can change `init_replica` not to do any schema alteration at the beginning.

**Comment by the4thdoctor** [comment]
Hi, I think is possible to have the init replica to just cleanup the existing data instead of recreate everything. 
I need to pickup the development again of this project which I left for too much unchanged.
I'll give it a look over the week end and will let you know if/when a new release will add this feature.

Ta!

**Comment by the4thdoctor** [comment]
Added to 2.0.13
