### ISSUE TITLE
Permissions needed in PostgreSQL for pg_chameleon replicas

### ISSUE THREAD

**Issue by OOCAZ** [the4thdoctor/pg_chameleon#118]
What are the exact permissions that pg_chameleon needs to do it's job in PostgreSQL? I don't want to use the postgres account.

**Comment by the4thdoctor** [comment]
And you shouldn't at any time use the postgres account as using a super user for normal operations is very dangerous.

Have a [look at the instruction please](https://pgchameleon.org/documents/usage.html#example).

> In PostgreSQL create a user for the replica and a database owned by the user

`CREATE USER usr_replica WITH PASSWORD 'replica';`
`CREATE DATABASE db_replica WITH OWNER usr_replica;`

**Comment by pyrite357** [comment]
@the4thdoctor I also would like to know the answer to this question. The docs do not explain what permissions are needed for PostgreSQL (see screenshot below). Are you saying that the defaults are OK? I was looking for a list of permissions like SELECT, UPDATE, CREATE DATABASE, etc. If it is just whatever the defaults are, I'll go research those. For MySQL however, the docs say "GRANT ALL ON ...", which gives the MySQL replica user all permissions. The question is what specific permissions are needed for each database so that this can be "least permissive". Thank you for your time and consideration of this question 👍 

![image](https://user-images.githubusercontent.com/1644542/89212861-dcced600-d589-11ea-930b-33108aa6faec.png)

**Comment by pyrite357** [comment]
@the4thdoctor sorry to bother man, but have you seen this yet?

**Comment by the4thdoctor** [comment]
sorry didn't notice the comment. 
I reckon that the permissions for MySQL are too high. However I remember a past issue (#65) where the replica did not work  because of the permissions too restrictive.
I ended with the permissions suggested in the docs during the initial build of the proof of concept.
