### ISSUE TITLE
pg_chameleon incompatible with PyMySQL==1.0.2

### ISSUE THREAD

**Issue by marvincorreia** [the4thdoctor/pg_chameleon#136]
**Describe the bug**
When I execute chameleon on terminal I get this error:
```
Traceback (most recent call last):
  File "/home/marvin/.local/bin/chameleon", line 5, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/marvin/.local/bin/chameleon.py", line 5, in <module>
    from pg_chameleon import replica_engine
  File "/home/marvin/.local/lib/python3.8/site-packages/pg_chameleon/__init__.py", line 2, in <module>
    from .lib.mysql_lib import *
  File "/home/marvin/.local/lib/python3.8/site-packages/pg_chameleon/lib/mysql_lib.py", line 7, in <module>
    from pymysqlreplication import BinLogStreamReader
  File "/home/marvin/.local/lib/python3.8/site-packages/pymysqlreplication/__init__.py", line 23, in <module>
    from .binlogstream import BinLogStreamReader
  File "/home/marvin/.local/lib/python3.8/site-packages/pymysqlreplication/binlogstream.py", line 9, in <module>
    from pymysql.util import int2byte
ModuleNotFoundError: No module named 'pymysql.util'
```

**To Reproduce**
```
pip install pg_chameleon
chameleon
```
**Expected behavior**
```
usage: chameleon [-h] [--config CONFIG] [--schema SCHEMA] [--source SOURCE] [--tables TABLES] [--logid LOGID] [--debug] [--version]
                 [--rollbar-level ROLLBAR_LEVEL] [--full]
                 command
chameleon: error: the following arguments are required: command
```
**Environment(please complete the following information):**
 - OS: ubuntu 20.04 LTS
 - Python Version 3.8

**How I solve the problem**
```
pip uninstall PyMySQL
pip install "PyMySQL==0.9.3"
```

**Comment by krisavi** [comment]
Problem you got from log seems to be in: https://github.com/noplay/python-mysql-replication
The pymsysqlreplication 0.22 should support PyMySQL version 0.9.3 and higher.
Connected to: https://github.com/noplay/python-mysql-replication/pull/337

I am not sure if you should downgrade to that low version to make it work, according to 
https://github.com/the4thdoctor/pg_chameleon/blob/9d80212541559c8d0a42b3e7c1b2c67bb7606411/setup.py#L53
it should work with 0.10.0, the 1.0.2 might be too new.  Change in PyMySQL was made in v1.0.0 to remove utils. Until it is fixed in python-mysql-replication probably you could downgrade to PyMySQL v0.10.1 to make it work. The utils did not seem to contain nothing else but byte2int unpack and int2byte pack, so I hope python-mysql-replication can update their code not to rely on utils that could be in their own repo if they need them or use Python internal functions as the pymysql.utils were not project specific, more like their internal helper functions that should not have been used by other projects at all.
