### ISSUE TITLE
Views replication?

### ISSUE THREAD

**Issue by ArturFormella** [the4thdoctor/pg_chameleon#3]
Hello!
Is it possible to replicate simple views?

For example only views containing primary key of a regular table and without "group by" clause, i.e:

```sql
CREATE VIEW USER_STATS as
	SELECT user.id, user.name, LPAD( user.sap_id,10,'0'), stats WHERE stats>0
```

It would be great to copy data without schema freezing.
Thanks!

**Comment by the4thdoctor** [comment]
Hi, as views are logical I should write a mysql to postgresql  translator. 
The lessons learned from the DDL replica make me very dubious about that. The procedure is working but is still having issues, I had to write my own regexp just because I had no other choice. And the small subset of statements I'm managing is still having issues (e.g. I still cannot generate a database replicating from an empty one). At moment I'm focusing on the procedure robustness doing as much bug fixes I can.

For the copy data without freezing, unfortunately this is the suggested procedure by MySQL documentation.
I think I can freeze, get the master coordinates and then copy the data using a transaction, but this will work only with innodb. 
I can explore this aspect in the version 2 I'm currently preparing.

Many thanks
