### ISSUE TITLE
force lowercase option

### ISSUE THREAD

**Issue by Hoya** [the4thdoctor/pg_chameleon#66]
My MySQL source has some old tables that use camelcase naming for table names and column names. It's a bit of a pain to work with on postgres which doesn't like camelcase naming.

It would be nice if there was an option to force all names to lowercase on the postgres destination.

**Comment by the4thdoctor** [comment]
Hi, in order to keep the replica working is not possible to force lower or uppercase.

However you can always create a set of views to lowercase the table's name.
As postgres supports the updatable views for simple definitions this is the solution that I suggest.

For example

``
CREATE VIEW mytable AS SELECT * FROM MyTable;
``

Will allow you to run select * from mytable and any DML should work out of the box.

More [details here](https://www.postgresql.org/docs/9.6/static/sql-createview.html)
